floodmapsv2/floodmapsv2/floodmaps/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import ListView, DetailView
from floodmapsv2.floodmaps.models import *
from floodmapsv2.floodmaps.views import SensorListView

urlpatterns = patterns('',
    #url(r'^$', 'floodmapsv2.floodmaps.views.create_map'),
)

floodmapsv2/floodmapsv2/predictive/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, ListView, DetailView
from predictive.models import *
from django.conf import settings

urlpatterns = patterns('',
    url(r'^$', ListView.as_view(model=UnitOfManagement, template_name="floods_dir_maps.html")),
    url(r'^apsr/(?P<pk>\d+)/$', DetailView.as_view(model=AreaOfPotentialSignificantRisk)),
    url(r'^extent/(?P<pk>\d+)/$', DetailView.as_view(model=FloodExtent)),
)

floodmapsv2/floodmapsv2/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
from django.contrib.gis import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', TemplateView.as_view(template_name="home.html")),
    url(r'^frm$', TemplateView.as_view(template_name="frm-home.html")),
    url(r'^map$', TemplateView.as_view(template_name="map.html")),
    url(r'^test-map$', TemplateView.as_view(template_name="test-map.html")),
    url(r'^predictive/', include('predictive.urls')),
    url(r'^test$', TemplateView.as_view(template_name="test.html")),

    # urls for apps
    #url(r'^$',include('floodmapsv2.floodmaps.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

floodmapsv2/floodmapsv2/geography/models.py
#from django.db import models
from django.contrib.gis.db import models

from south.modelsinspector import add_introspection_rules
add_introspection_rules([], ["^django\.contrib\.gis"])


# Create your models here.

# Coast
class Coast(models.Model):
    attribute = models.CharField(max_length=5)
    style = models.CharField(max_length=255,blank=True,null=True)

    # geometry
    geometry = models.MultiPolygonField(srid=2157)
    objects = models.GeoManager() 
    
    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.attribute)
    class Meta:
        ordering = ['attribute']

# Province
class Province(models.Model):
    name = models.CharField(max_length=20)
    style = models.CharField(max_length=255,blank=True,null=True)
    area_sq_km = models.FloatField(blank=True,null=True)
    perimiter_km = models.FloatField(blank=True,null=True)

    # geometry
    geometry = models.MultiPolygonField(srid=2157)
    objects = models.GeoManager()

    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']


# County
class County(models.Model):
    name = models.CharField(max_length=40)
    irish_name = models.CharField(max_length=40)
    style = models.CharField(max_length=255,blank=True,null=True)

    # geometry
    geometry = models.MultiPolygonField(srid=2157)
    objects = models.GeoManager()

    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'counties'

# DED
class DistrictElectoralDivision(models.Model):
    name = models.CharField(max_length=40)
    county = models.ForeignKey(County)

    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']

# Town
class Town(models.Model):
    name = models.CharField(max_length=50)
    name_and_county = models.CharField(max_length=35)
    county = models.ForeignKey(County)
    centroid_x = models.FloatField()
    centroid_y = models.FloatField()
    irish_name = models.BooleanField()
    irish_class = models.CharField(max_length=30)
    town_category = models.IntegerField()
    source = models.CharField(max_length=25)

    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']

# Townland
class Townland(models.Model):
    name = models.CharField(max_length=50)
    os_townland_id = models.IntegerField()
    county = models.ForeignKey(County)
    ded = models.ForeignKey(DistrictElectoralDivision)
    upper = models.CharField(max_length=50)

    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']


# Coastal waters
class CoastalWater(models.Model):
    name = models.CharField(max_length=50)
    # coastal_area

    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']

# Catchments
class Catchment(models.Model):
    number = models.CharField(max_length=13) # EPA number
    name = models.CharField(max_length=40)
    style = models.CharField(max_length=255,blank=True,null=True)
    area_sq_km = models.FloatField(blank=True,null=True)
    perimiter_km = models.FloatField(blank=True,null=True)
    hydrometric_area = models.IntegerField()
    #rbd
    
    # geometry
    geometry = models.MultiPolygonField(srid=2157)
    objects = models.GeoManager()

    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name','hydrometric_area']

# Roads
class Road(models.Model):
    mapflow_id = models.FloatField() # Mapflow ID
    name = models.CharField(max_length=50)
    approx_region = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    geosid = models.FloatField()
    nra_name = models.CharField(max_length=10)
    code = models.FloatField()
    fre = models.FloatField()
    approx_region_city_name = models.CharField(max_length=75)
    town = models.ForeignKey(Town)
    style = models.CharField(max_length=255,blank=True,null=True)
    # geometry
    geometry = models.MultiPolygonField(srid=2157)
    objects = models.GeoManager()

    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']

# Lakes
class Lake(models.Model):
    seg_cd = models.CharField(max_length=24) # EPA ref
    name = models.CharField(max_length=50)
    style = models.CharField(max_length=255,blank=True,null=True)
    area_sq_km = models.FloatField(blank=True,null=True)
    perimiter_km = models.FloatField(blank=True,null=True)
    hydrometric_area = models.IntegerField()
    #rbd
    
    # geometry
    geometry = models.MultiPolygonField(srid=2157)
    objects = models.GeoManager()

    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name','hydrometric_area']

# Rivers
class River(models.Model):
    epa_code = models.CharField(max_length=20)
    name = models.CharField(max_length=50)
    style = models.CharField(max_length=255,blank=True,null=True)
    catchment = models.ForeignKey(Catchment)
    flow_direction = models.CharField(max_length=1)
    length = models.FloatField()
    up_stream_length = models.FloatField()
    down_stream_length = models.FloatField()

    # geometry
    geometry = models.MultiPolygonField(srid=2157)
    objects = models.GeoManager()

    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']

floodmapsv2/floodmapsv2/historic_properties/models.py
from django.db import models

# Create your models here.

floodmapsv2/floodmapsv2/indicative/models.py
from django.contrib.gis.db import models

# Create your models here.
## Indicative Floods
# indicative flood polygons
class IndicativeFloodDataset(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255,null=True,blank=True)
    abstract = models.TextField(null=True,blank=True)
    metadata = models.URLField(null=True,blank=True)
    # release_version

    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']

class IndicativeFloodCategory(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255,null=True,blank=True)
    
    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'indicative flood categories'
        
class IndicativeFlood(models.Model):
    dataset = models.ForeignKey(IndicativeFloodDataset)
    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=50)
    category = models.ForeignKey(IndicativeFloodCategory)
    # geometry
    geometry = models.MultiPolygonField(srid=2157)
    objects = models.GeoManager()
    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']

floodmapsv2/floodmapsv2/monuments/models.py
from django.db import models

# Create your models here.

floodmapsv2/floodmapsv2/predictive/models.py
from django.contrib.gis.db import models

# Create your models here.
# PFRA
class Status(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255,null=True,blank=True)
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']   
        verbose_name_plural = 'status'

class VersionType(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255,null=True,blank=True)
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']

class Availability(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255,null=True,blank=True)
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'availability'

class UnitOfManagement(models.Model):
    name = models.CharField(max_length=50)
    rbd = models.BooleanField(default=True)
    acronym = models.CharField(max_length=10) 
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']   
        verbose_name_plural = 'units of management'
        
class AreaOfPotentialSignificantRisk(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255,null=True,blank=True)
    uom = models.ForeignKey(UnitOfManagement)
    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now=True)
    
    # geometry
    geometry = models.MultiPolygonField(srid=2157)
    objects = models.GeoManager()
    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']   
        verbose_name_plural = 'areas of potential significant risk'
        
class Climate(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255,null=True,blank=True)
    acronym = models.CharField(max_length=10) 
    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']

class AnnualExceedanceProbability(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255,null=True,blank=True)
    acronym = models.CharField(max_length=10)
    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'annual exceedance probabilities'

class Source(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255,null=True,blank=True)
    acronym = models.CharField(max_length=10)
    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']

class Scenario(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255,null=True,blank=True)
    climate = models.ForeignKey(Climate)
    aep = models.ForeignKey(AnnualExceedanceProbability)
    source = models.ForeignKey(Source)
    acronym = models.CharField(max_length=10)
    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']

class UncertaintyBand(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255,null=True,blank=True)
    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.name)
    class Meta:
        ordering = ['name']
          
class Node(models.Model):
    name = models.CharField(max_length=50)
    apsr = models.ForeignKey(AreaOfPotentialSignificantRisk)
    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now=True)
    
    # geometry
    geometry = models.PointField(srid=2157)
    objects = models.GeoManager()
    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.parent)
    class Meta:
        ordering = ['name']
        
class NodeValue(models.Model):
    scenario = models.ForeignKey(Scenario)
    node = models.ForeignKey(Node)
    elevation = models.FloatField()
    flow = models.FloatField()
    depth = models.FloatField()
    velocity = models.FloatField()
    
    def __unicode__(self):
        return '%s %s' % (self.node, self.scenario)
    class Meta:
        ordering = ['node']

class FloodExtent(models.Model):
    apsr = models.ForeignKey(AreaOfPotentialSignificantRisk)
    apsr_m2m = models.ManyToManyField(AreaOfPotentialSignificantRisk,null=True,blank=True, related_name="apsr_m2m")
    scenario = models.ForeignKey(Scenario)
    status = models.ForeignKey(Status)
    version_type = models.ForeignKey(VersionType)
    availability = models.ForeignKey(Availability)
    # metadata
    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now=True)
    # geometry
    geometry = models.MultiPolygonField(srid=2157)
    objects = models.GeoManager()
    
    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s %s' % (self.status, self.scenario)
    #class Meta:
        #ordering = ['apsr']
    
class Uncertainty(models.Model):
    extent = models.ForeignKey(FloodExtent)
    uncertainty_band = models.ForeignKey(UncertaintyBand)
    
    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now=True)
    # geometry
    geometry = models.MultiLineStringField(srid=2157)
    objects = models.GeoManager()
    
    # Returns the string representation of the model.
    def __unicode__(self):
        return '%s' % (self.parent)
    class Meta:
        ordering = ['extent']
        verbose_name_plural = 'flood extent uncertainties'

# predictive flood depth (grid?)

# predictive flood velocity (grid?)

# predictive flood risk (grid?)

floodmapsv2/floodmapsv2/property/models.py
from django.db import models

# Create your models here.

floodmapsv2/floodmapsv2/historic_properties/views.py
# Create your views here.

floodmapsv2/floodmapsv2/monuments/views.py
# Create your views here.

floodmapsv2/floodmapsv2/property/views.py
# Create your views here.

floodmapsv2/floodmapsv2/templates/predictive/areaofpotentialsignificantrisk_detail.html
{% extends "base_template.html" %}

{% block title %}Floods Directive maps - {{ object }}{% endblock %}
{% block header %}
    <link href="/static/detail.css" rel="stylesheet" type="text/css" >
    <script src="/static/js/OpenLayers-2.12/OpenLayers.js" type="text/javascript"></script>
    <script src="/static/js/proj4js/lib/proj4js-compressed.js" type="text/javascript"></script>
    <link href="/static/js/OpenLayers-2.12/theme/default/style.css" rel="stylesheet" type="text/css" >
    <script type="text/javascript">
        OpenLayers.IMAGE_RELOAD_ATTEMPTS = 1;
        OpenLayers.Util.onImageLoadErrorColor = "transparent"; 
        Proj4js.defs["EPSG:2157"] = "+proj=tmerc +lat_0=53.5 +lon_0=-8 +k=0.99982 +x_0=600000 +y_0=750000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs";
        Proj4js.defs["EPSG:29903"] = "+proj=tmerc +lat_0=53.5 +lon_0=-8 +k=1.000035 +x_0=200000 +y_0=250000 +a=6377340.189 +b=6356034.447938534 +towgs84=482.5,-130.6,564.6,-1.042,-0.214,-0.631,8.15 +units=m +no_defs";
        Proj4js.defs["EPSG:3857"] = "+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs";
        var WebMercator = new OpenLayers.Projection("EPSG:900913");
        var WGS84 = new OpenLayers.Projection("EPSG:4326");
        var ING = new OpenLayers.Projection("EPSG:29903");
        var ITM = new OpenLayers.Projection("EPSG:2157");
        var WM = new OpenLayers.Projection("EPSG:3857");
        var bounds_WM = new OpenLayers.Bounds(-1200000, 6800000, -420000, 7250000);
        var controls = [
            new OpenLayers.Control.Attribution(),
            new OpenLayers.Control.PanZoomBar(),
            new OpenLayers.Control.Navigation(),
            new OpenLayers.Control.LayerSwitcher(),
            new OpenLayers.Control.Scale(document.getElementById('scale')),
            new OpenLayers.Control.MousePosition({displayProjection: ING,'div':OpenLayers.Util.getElement('coords')})
            ];
        var options = {
                numZoomLevels: 14,
                units: 'm',
                controls: controls,
                maxExtent: bounds_WM,
                resolutions: [1000,352.645,176.32242,74.0542,52.896723,35.26448,26.448362,17.632241,8.816121,3.526448,1.763224,0.881612,0.352645],
                projection: ITM
            };
        var wkt =  '{{ object.geometry.wkt|safe }}';
        
        var format = new OpenLayers.Format.WKT({
            'internalProjection': WebMercator, //map.baseLayer.projection,
            'externalProjection': ITM //new OpenLayers.Projection("EPSG:2157")
            });

        var polygonFeature= format.read(wkt);
        
        function init() {
            
            var map = new OpenLayers.Map("map",options);
            var osm = new OpenLayers.Layer.OSM();
            var mapfile = '/opt/projects/floodmapsv2/floodmapsv2/floodmapsv2/mapserv.map';
            var wms_server = '/cgi-bin/mapserv?map='+mapfile;
            var extents = new OpenLayers.Layer.WMS('1% AEP Fluvial', wms_server,
            {
                //SERVICE: 'WMS', VERSION: '1.1.1', REQUEST: 'GetMap',
                srs: WM,
                transparent: true,
                layers: 'Flood_extents_1pc_AEP',
                format: "image/png"
            },
            {isBaseLayer: false, opacity: 0.6});
            
            var apsr = new OpenLayers.Layer.WMS('APSR', wms_server,
            {
                //SERVICE: 'WMS', VERSION: '1.1.1', REQUEST: 'GetMap',
                srs: WM,
                transparent: true,
                layers: 'apsr',
                format: "image/png"
            },
            {isBaseLayer: false, opacity: 0.6});
            
            var vector = new OpenLayers.Layer.Vector("Areas for further assessment");
            vector.addFeatures([polygonFeature]);
            
            var wfsAPSR = new OpenLayers.Layer.Vector("Areas for further assessment (WFS)", {
                strategies: [new OpenLayers.Strategy.BBOX()],
                protocol: new OpenLayers.Protocol.WFS({
                      "url": wms_server,
                      //"propertyNames": propertyNames,
                      "geometryName": "msGeometry",
                      "featureType": "apsr",
                      "featurePrefix": "ms",
                      "srsName": "EPSG:2157",
                      "maxFeatures": 1000,
                      "version": "1.1.0"
                  })
            });
            
            wfsAPSR.events.on({
                featureselected: function(event) {
                    var feature = event.feature;
                    var area = feature.geometry.getArea()/10000.0;
                    var id = feature.attributes.name;
                    var output = "Name: " + id + " Area: " + area.toFixed(2) + " Ha";
                    document.getElementById("output-id").innerHTML = output;
                }
            });

            var wfsExtents = new OpenLayers.Layer.Vector("Predicted Flood Extents (WFS)", {
                strategies: [new OpenLayers.Strategy.BBOX()],
                protocol: new OpenLayers.Protocol.WFS({
                      "url": wms_server,
                      //"propertyNames": propertyNames,
                      "geometryName": "msGeometry",
                      "featureType": "Flood_extents_1pc_AEP",
                      "featurePrefix": "ms",
                      "srsName": "EPSG:2157",
                      "maxFeatures": 1000,
                      "version": "1.1.0"
                  })
            });
            
            var select = new OpenLayers.Layer.Vector("Selection", {styleMap: 
                new OpenLayers.Style(OpenLayers.Feature.Vector.style["select"])
            });
            var hover = new OpenLayers.Layer.Vector("Hover");
            
            var control = new OpenLayers.Control.GetFeature({
                protocol: OpenLayers.Protocol.WFS.fromWMSLayer(apsr),
                box: true,
                hover: true,
                multipleKey: "shiftKey",
                toggleKey: "ctrlKey"
            });
            control.events.register("featureselected", this, function(e) {
                select.addFeatures([e.feature]);
            });
            control.events.register("featureunselected", this, function(e) {
                select.removeFeatures([e.feature]);
            });
            control.events.register("hoverfeature", this, function(e) {
                hover.addFeatures([e.feature]);
            });
            control.events.register("outfeature", this, function(e) {
                hover.removeFeatures([e.feature]);
            });
            //map.addControl(control);
            //control.activate();
            
            wfsExtents.events.on({
                featureselected: function(event) {
                    var feature = event.feature;
                    var area = feature.geometry.getArea()/10000.0;
                    var id = feature.attributes.scenario_id;
                    var output = "Name: " + id + " Area: " + area.toFixed(2) + " Ha";
                    document.getElementById("output-id").innerHTML = output;
                }
            });
                        
            map.addLayers([osm, extents, wfsExtents, wfsAPSR, vector]);
            //map.addLayers([osm, extents, apsr, select, hover])
            
            var select_extent = new OpenLayers.Control.SelectFeature([wfsExtents, wfsAPSR]);
            map.addControl(select_extent);
            select_extent.activate();
            

            //map.zoomToExtent(bounds_WM);
            map.zoomToExtent(polygonFeature.geometry.getBounds());
        }
        function sync_data() {
            
        }
    </script>
{% endblock %}{% block headbody %}</head>
<body onload="init()" >{% endblock %}
{% block menu-bar %}
    {% include "header.html" %}
    {% include "menu-bar.html" %}</div>
{% endblock %}

{% block page_body %}
<h1>Floods Directive</h1>
<div class="left">
<h2>Details for {{ object }}</h2>
<p>{{ object.name }}</p>
<div id="map" class="smallmap"  style="height:400px;width:95%;"></div><div id="scale"></div><div id="coords"></div>
<div id="output-id"></div>
</div>
<div class="right">
Modelled Scenario (Status)
{% for s in object.apsr_m2m.all %}
<li><a href="../../extent/{{s.id}}/">{{s.scenario}}</a> ({{s.status}})</li>
{% endfor %}
</div>
{% endblock %}

floodmapsv2/floodmapsv2/templates/predictive/floods_dir_maps.html
{% extends "base_template.html" %}

{% block title %}Floods Directive maps{% endblock %}
{% block header %}
    <link href="/static/detail.css" rel="stylesheet" type="text/css" >
{% endblock %}
{% block menu-bar %}
    {% include "header.html" %}
    {% include "menu-bar.html" %}</div>
{% endblock %}

{% block page_body %}

<h1>Floods Directive</h1>
<div class="left">
<h2>Areas for Further Assessment</h2><p>(Areas of Potential Significant Risk)</p>
{% for u in object_list %}
<p>{{ u.name }}
<ul>
{% for s in u.areaofpotentialsignificantrisk_set.all %}
<li><a href="apsr/{{s.id}}">{{s.name}}</a></li>
{% endfor %}
</ul>
</p>
{% endfor %}

</div>
<div class="right">

</div>
{% endblock %}